### ISSUE TITLE
Server.pro, MC 1.17 - java.lang.reflect.InaccessibleObjectException

### ISSUE THREAD

**Issue by WillyJL** [ServerJars/updater#12]
Can't seem to get this to work :/
Hosting: server.pro, 2GB ram - 20GB storage - 2 vCores
MC: Spigot 1.17

```
   _____                               __               
  / ___/___  ______   _____  _____    / /___ ___________
  \__ \/ _ \/ ___/ | / / _ \/ ___/_  / / __ `/ ___/ ___/
 ___/ /  __/ /   | |/ /  __/ /  / /_/ / /_/ / /  (__  ) 
/____/\___/_/    |___/\___/_/   \____/\__,_/_/  /____/  
ServerJars.com           Made with love by Songoda <3
ServerJars is starting...
Downloading jar...
Jar updated successfully.
Launching spigot-1.17.jar...
.............................
Exception in thread "main" java.lang.reflect.InaccessibleObjectException: Unable to make protected void java.net.URLClassLoader.addURL(java.net.URL) accessible: module java.base does not "opens java.net" to unnamed module @50828c64
at java.base/java.lang.reflect.AccessibleObject.checkCanSetAccessible(Unknown Source)
at java.base/java.lang.reflect.AccessibleObject.checkCanSetAccessible(Unknown Source)
at java.base/java.lang.reflect.Method.checkCanSetAccessible(Unknown Source)
at java.base/java.lang.reflect.Method.setAccessible(Unknown Source)
at com.songoda.serverjars.ServerJars.addClasspath(ServerJars.java:223)
at com.songoda.serverjars.ServerJars.getMainMethod(ServerJars.java:253)
at com.songoda.serverjars.ServerJars.main(ServerJars.java:79)
```

**Comment by SpraxDev** [comment]
Thanks for your report - A fix will be release in the next update.
