### ISSUE TITLE
App crashes on invalid type or version in config

### ISSUE THREAD

**Issue by DartPower** [ServerJars/updater#2]
```
   _____                               __
  / ___/___  ______   _____  _____    / /___ ___________
  \__ \/ _ \/ ___/ | / / _ \/ ___/_  / / __ `/ ___/ ___/
 ___/ /  __/ /   | |/ /  __/ /  / /_/ / /_/ / /  (__  )
/____/\___/_/    |___/\___/_/   \____/\__,_/_/  /____/
ServerJars.com           Made with love by Songoda <3

ServerJars is starting...
Exception in thread "main" java.lang.NullPointerException
        at com.songoda.serverjars.ServerJars.setupEnv(ServerJars.java:172)
        at com.songoda.serverjars.ServerJars.main(ServerJars.java:65)
```

```
#Acceptable Versions (latest, 1.16.4, 1.8, etc...)
#Fri Jan 08 21:55:30 MSK 2021
version=1.7.10
type=spigot
```

**Comment by DartPower** [comment]
```
openjdk version "1.8.0_272"
OpenJDK Runtime Environment (AdoptOpenJDK)(build 1.8.0_272-b10)
OpenJDK 64-Bit Server VM (AdoptOpenJDK)(build 25.272-b10, mixed mode)
```

**Comment by DartPower** [comment]
Oh... this is because 1.7.10 builds not hosting. Ok

**Comment by Im-Fran** [comment]
I've released an update that automatically uses the latest jar if the version you specified is not found.
![image](https://user-images.githubusercontent.com/30329003/179881299-856c5ce8-34af-4b33-85f3-d76a62933adb.png)

This is the same with the server type.
