### ISSUE TITLE
javax.net.ssl.SSLHandshakeException on Java 11

### ISSUE THREAD

**Issue by jonttm** [ServerJars/updater#4]
I get this error when trying to download paper.jar on Java 11. It only happens on Java 11, not on Java 8. 

My config is paper, latest. 

```
javax.net.ssl.SSLHandshakeException: Received fatal alert: handshake_failure
at java.base/sun.security.ssl.Alert.createSSLException(Unknown Source)
at java.base/sun.security.ssl.Alert.createSSLException(Unknown Source)
at java.base/sun.security.ssl.TransportContext.fatal(Unknown Source)
at java.base/sun.security.ssl.Alert$AlertConsumer.consume(Unknown Source)
at java.base/sun.security.ssl.TransportContext.dispatch(Unknown Source)
at java.base/sun.security.ssl.SSLTransport.decode(Unknown Source)
at java.base/sun.security.ssl.SSLSocketImpl.decode(Unknown Source)
at java.base/sun.security.ssl.SSLSocketImpl.readHandshakeRecord(Unknown Source)
at java.base/sun.security.ssl.SSLSocketImpl.startHandshake(Unknown Source)
at java.base/sun.net.www.protocol.https.HttpsClient.afterConnect(Unknown Source)
at java.base/sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(Unknown Source)
at java.base/sun.net.www.protocol.https.HttpsURLConnectionImpl.connect(Unknown Source)
at com.serverjars.api.ServerJars.sendRequest(ServerJars.java:49)
at com.serverjars.api.request.LatestRequest.send(LatestRequest.java:38)
at com.songoda.serverjars.ServerJars.setupEnv(ServerJars.java:161)
at com.songoda.serverjars.ServerJars.main(ServerJars.java:63)
Exception in thread "main" java.lang.NullPointerException
at com.songoda.serverjars.ServerJars.setupEnv(ServerJars.java:172)
at com.songoda.serverjars.ServerJars.main(ServerJars.java:63)
```

**Comment by SpraxDev** [comment]
Is your issue still happening? Looks like a temporary server issue to me.

**Comment by jonttm** [comment]
I don’t know. I stopped using ServerJars a while ago.
